name: Clone Repos

on: [push]

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
      - name: Clone kool repo
        run: |
          git clone https://github.com/vinaybv77716/kool.git

      - name: Clone terraform-eks repo
        run: |
          git clone https://github.com/vinaybv77716/terraform-eks.git
