name: CI

on: [push]


jobs:
  build:
    runs-on: self-hosted
    steps:
     - name: Check out the repo
       run: rm -rf diatoz_assinment && git clone https://github.com/vinaybv77716/diatoz_assinment.git
     - name: Check docker version
       run: docker --version
     # - name: build docker image and push to ecr repo
     #   run: |
     #      sudo apt update
     #      sudo chown $USER /var/run/docker.sock
     #      aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 890405391444.dkr.ecr.us-east-1.amazonaws.com
     #      docker build -t nodeproj diatoz_assinment/.
     #      docker tag nodeproj:latest 890405391444.dkr.ecr.us-east-1.amazonaws.com/nodeproj:latest
     #      docker push 890405391444.dkr.ecr.us-east-1.amazonaws.com/nodeproj:latest
